print("creating set")
set1={1,2,3,4,5}
print(set1)
print("adding value")
set1.add("moiz")
print(set1)
print("removing value")
set1.remove("moiz")
print(set1)
print("discaring value")
set1.discard(5)
print(set1)
print("clearing set")
set1.clear()
print(set1)
